version: "3.9"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  server1: &srv
    build: ./server
    environment:
      - SERVICE_PORT=18861
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATA_DIR=/app/data
    depends_on: [redis]
    restart: unless-stopped

  server2:
    <<: *srv

  server3:
    <<: *srv

  lb:
    build: ./server
    depends_on: [server1, server2, server3]
    environment:
      - ALGO=rr
      - LB_PORT=9000
    command: ["python", "load_balancer.py"]
    ports:
      - "9000:9000"
    restart: unless-stopped

  client:
    build: ./client
    depends_on: [lb]
    environment:
      - SERVER_HOST=lb
      - RPYC_PORT=9000
      - TWO_PASSES=1
      - SAVE_CSV=1
    volumes:
      - ./results:/results
    command: ["python", "client.py"]
    restart: "no"
