version: "3.9"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  server1:
    build: ./server
    environment:
      - SERVICE_PORT=18861
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATA_DIR=/app/data
    depends_on: [redis]
    restart: unless-stopped

  client:
    build: ./client
    depends_on: [server1]
    environment:
      - SERVER_HOST=server1
      - RPYC_PORT=18861
      - TWO_PASSES=1
      - SAVE_CSV=0
      - TIME_BETWEEN=0.1
      - INF_PASS=0
      - SAMPLE_SIZE=20
      - JITTER=0
    volumes:
      - ./results:/results
    command: ["python", "client.py"]
    restart: no
